// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { ReconnectToken } from "./ReconnectToken";
import type { RoomId } from "./RoomId";
import type { UserId } from "./UserId";

export type ClientMessage = { type: "join_room", username: string, room: RoomId | null, } | { type: "rejoin_room", token: ReconnectToken, room: RoomId, } | { type: "update_config", config: any, } | { type: "start_game", player_mapping: Record<UserId, PlayerId> | null, } | { type: "do_action", action: any, };